### ISSUE TITLE
Compatibility with Winbond w25q128jv

### ISSUE THREAD

**Issue by SpyrosMourelatos** [lixpaulian/stm32f7-qspi#1]
Is this class really compatible with the jv series? While compering winbond datasheets I noticed they have some different bits on their REG1 and REG2 (e.g. the quad spi enable bit). I can't find any of those bitmasks on the codebase and I imagine they are hard coded for all the winbond devices, am I correct ?

**Comment by lixpaulian** [comment]
Hello DM,

For each flash chip there is a special file; for the time being, only two main types are supported, one from Micron, the other from Winbond. Time allowing, and if I get my hand on other flash chips I will add support for them in the future.

So to your question, most commands are identical, however, where they differ speciffic code is instantiated at run-time (after the flash type has been detected) to implement these commands. And yes, you are right, switching to quad mode differs and for the Winbond flash is implemented in the function _qspi_winbond::enter_quad_mode_ in the file _qspi-winbond.cpp_. All other minor differences (eg. dummy cycles) are specified in the flashes' tables in the file _qspi-descr.cpp_.

Did you really check all the files of the project?

**Comment by SpyrosMourelatos** [comment]
Yes I studied t the codebase thoroughly before issuing an issue and specifically winbond.cpp and description.cpp. I just noticed that you handle the jv model the exact same way as the fv even though their datasheets state that their registers are quite different

**Comment by lixpaulian** [comment]
Sorry, I misunderstood you, I assumed you mean differences in quad mode between Micron and Winbond, while you actually meant differences between various Winbond types (JV & FV).

Fact is, I never stumbled upon the plain JV model, rather the JV-DTR (dual transfer rate). You might be right that with the standard JV the driver might not work, however I can't affirm or infirm this as I have no way to test it. For your convenience, here is a [link](https://www.winbond.com/resource-files/w25q128jv_dtr%20revc%2003272018%20plus.pdf) to the specs of the flash chips I am using (W25Q128JVSIM). BTW, there are almost 1000 pcs of a product out there in field using this driver and this chip.

I find the way Winbond marks its chips unfortunate and confusing. For the SOIC-8 part the DTR chips are named W25Q128JVSIM and marked 25Q128JVSM, while the non-DTR chips are named W25Q128JVSJM and marked Q128JVSJM. You may want to check the marking of your chips, if they are marked 25Q128JVSM, then you're ok with the driver; if the "25" is missing, then probably you're not.

Anyway, thanks for pointing this to me, I guess that for the time being the entry in the _winbond_devices_ table with the Device ID 0x4018 should be removed (see _qspi-descr.cpp_) as they do not seem to be compatible. The main difference with these devices is that they don't support the so-called "QPI mode" (and thus dual rate). You may get around this issue by removing the code enabling QPI (lines 88 to 92 in _qspi-winbond.cpp_) and see if it works, as everything else should be identical (the driver makes currently no use of dual rate instructions).

Let me know how it went out. If I manage to get my hands on one of these chips, I will test by myself.

**Comment by SpyrosMourelatos** [comment]
Sorry I only needed these driver for a bootloader (which didn't require μos ) so I wrote one manually with cubeMx HAL. I believe that the main difference you should address is to completely skip quad_enable on the jv series

**Comment by lixpaulian** [comment]
I don't agree with your conclusion. One one hand, the JV types you are using are probably obsolete, all of the JVs currently on the market support QPI (just checked DigiKey and Mouser).

On the other hand, don't confuse quad operation with QPI operation. The difference between QPI and non-QPI parts is (apart from the double data rate) the way the instructions are sent: the QPI parts accept/expect instructions on 4 lines, while the others only on one line. However, both are quad operation capable. All JVs can be switched to quad mode by setting the bit S9 (QE) in the Status Register 2.

However, as the current driver is written, it always uses instructions on 4 lines. This can be changed if the _InstructionMode_ in the _QSPI_CommandTypeDef_ structure is changed from _QSPI_INSTRUCTION_4_LINES_ to _QSPI_INSTRUCTION_1_LINE_. But as I don't have such a chip to test, I can't do it for now. What I can do, is to add a warning in the _readme_ for those happening to use such chips. And as I already said, I will eliminate the ID 0x4018 (coresponding to the non-QPI parts) from the _winbond_devices_ table.

**Comment by SpyrosMourelatos** [comment]
No I am sorry I didn't meant to disable quadspi completely. I meant that they are by default pre-configured to quad spi and they don't need that command due to the documentation on page 15 on that [datasheet](https://www.digikey.gr/en/datasheets/winbond-electronics/winbond-electronicsw25q128jv20spi20revc2011162016#pf10)

> The Quad Enable (QE) bit is set to 1 by default in the factory, therefore the device supports Standard/Dual SPI as well as Quad SPI after power on. This bit cannot be reset to 0. Note: QE bit is set to a 0 state, factory default for  part  numbers  with  ordering  options  “IM; please see W25Q128JV-DTR data sheet

**Comment by lixpaulian** [comment]
In the latest [datasheet](https://www.winbond.com/resource-files/W25Q128JV%20RevH%2003102021%20Plus.pdf) (Revison H, March 10, 2021) for this part posted on the Winbond web site, they say:

> The Quad Enable (QE) bit is a non-volatile read/write bit in the status register (S9) that enables Quad SPI operation. When the QE bit is set to a 0 state (factory default for part numbers with ordering options “IM” & “JM”), the /HOLD is enabled, the device operates in Standard/Dual SPI modes. When the QE bit is set to a 1 (factory fixed default for part numbers with ordering options “IQ/IN” & “JQ”), the Quad IO2 and IO3 pins are enabled, and /HOLD function is disabled, the device operates in Standard/Dual/Quad SPI modes.

Therefore it is not that easy for a generic solution. Probably there are two things to be done after identifying the part (ID 0x4018): skip switching it to Quad mode as it is by default in this state, and send all commands on one line instead of four.

As I don't have such a chip on hand, I cannot do this without testing. Therefore I will eliminate for now the 0x4018 ID from the table with a note in the _read me_. In the fall 2021 there will be a minor update to the driver and it will include these changes.

Thank you for pointing me out this issue.

**Comment by lixpaulian** [comment]
In the latest version of the driver (2.2.4) the Winbond memories with the IDs 0x4016, 0x4017 and 0x4018 have been removed as they do not support QPI mode. The driver currently does not support chips in Quad mode without QPI. In QPI mode, the instruction is also sent on 4 wires whereas in quad SPI mode the instruction is always sent on one wire. I should be no problem to support this mode, but as I don't have such a chip, I cannot test it, therefore I prefer to remove them from the table. I am open to contributions if someone has done it.
